version: '3'
services:
  deploy:
    build:
      context: .
      args:
        - PORT=8000
        - DB_NAME=hydro
        - ATLAS_URI=mongodb+srv://tzou2024:pswd@cluster0.ivgfrft.mongodb.net/?retryWrites=true&w=majority
      dockerfile: Dockerfile
    ports:
      - '80:8000'