name: black-action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/black-check@master
        with:
          black_args: "app/ tests/ --check --line-length 79 -v"
