name: Deploy to lambda

on: [pull_request]

jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run:
          mkdir site-packages && pip install -r requirements.txt -t
          site-packages
      - name: build zip
        run: |
          cd site-packages && zip -r9 ../deployment.zip . && cd ../App/server && zip -g ../../deployment.zip app.py
      - name: deploy to lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: hydrangea
          zip_file: deployment.zip
