name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_docker_images:
    name: build docker images
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        logout: true
    - name: Build Server image
      run: docker build --build-arg "DB_NAME={{ secrets.DB_NAME }}"  --build-arg "ATLAS_URI={{ secrets.ATLAS_URI }}"  --build-arg "PORT={{ secrets.PORT }}" -t tzou2024/hydroapi -f Dockerfile .
    - name: Tag our Image
      run: docker tag tzou2024/hydroapi tzou2024/hydroapi:latest
    - name: Push to dockerhub
      run: docker push tzou2024/hydroapi


    -
      name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
        
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: hydro-api
        environment_name: hydroapi-env
        version_label: "app-35be-221210_150837000421"
        region: us-east-1
    
    

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#       with:
#         lfs: 'true'
#     - 
#       name: Build the Docker image
#       run: docker build --build-arg "DB_NAME=8000"  --build-arg "ATLAS_URI=mongodb+srv://tzou2024:pswd@cluster0.ivgfrft.mongodb.net/?retryWrites=true&w=majority"  --build-arg "PORT=8000" -t tzou2024/hydroapi -f Dockerfile .
#     -
#       name: Generate Deployment Package
#       run: zip -r deploy.zip *
#     -
#       name: Get timestamp
#       uses: gerred/actions/current-time@master
#       id: current-time
        
#     - name: Run string replace
#       uses: frabert/replace-string-action@master
#       id: format-time
#       with:
#         pattern: '[:\.]+'
#         string: "${{ steps.current-time.outputs.time }}"
#         replace-with: '-'
#         flags: 'g'

#     - name: Deploy to EB
#       uses: einaregilsson/beanstalk-deploy@v14
#       with:
#         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         application_name: hydro-api
#         environment_name: Hydroapi-env
#         version_label: "hydro-api-${{ steps.format-time.outputs.replaced }}"
#         region: us-east-1
#         deployment_package: deploy.zip